#!/bin/sh
OPTS=...

echo 408 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio408/direction
echo 1 > /sys/class/gpio/gpio408/value

sleep 5

echo 0 > /sys/class/gpio/gpio408/value
sleep 0.1
echo 1 > /sys/class/gpio/gpio408/value

avrdude_org $@

echo 408 > /sys/class/gpio/unexport

